#!/usr/bin/python3
# Programed by M.kawase
# 組込AI研究所
# ラズベリーパイPIカメラ
# 画像読み取り部

import time
import cv2
import sys

maxpic = 8

st=1.0
dev='/dev/video0'
cap = cv2.VideoCapture(dev)
cap.set(cv2.CAP_PROP_FRAME_WIDTH, 320)
cap.set(cv2.CAP_PROP_FRAME_HEIGHT, 240)

if not cap.isOpened():
    sys.exit()

while True:
    r, frm = cap.read()
    if r:
        ts=str(int(time.time()/st) % maxpic)
        cv2.imwrite('images/cap'+ts+'.jpg',frm)
        time.sleep(st)
        if (cv2.waitKey(1) & 0xff) == ord('q'):
            break
    else:
       break

